openapi: 3.1.0
info:
  title: Safe Transaction Service 4337 owners API
  version: 6.3.0
  description: API to keep track of transactions sent via Safe smart contracts
tags:
- name: owners
paths:
  /tx-service/eth/api/v1/owners/{address}/safes/:
    get:
      operationId: owners_safes_retrieve
      description: Returns the list of Safe accounts that have the given address as their owner
      parameters:
      - in: path
        name: address
        schema:
          type: string
        required: true
      tags:
      - owners
      security:
      - cookieAuth: []
      - tokenAuth: []
      - {}
      deprecated: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnerResponse'
          description: ''
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeErrorResponse'
          description: Owner address checksum not valid
      path: /tx-service/eth/api/v1/owners/{address}/safes/
      title: ''
      additionalInfo: ''
  /tx-service/eth/api/v2/owners/{address}/safes/:
    get:
      operationId: owners_safes_list
      description: Returns a paginated list of Safe accounts that have the given address as their owner.
      parameters:
      - in: path
        name: address
        schema:
          type: string
        required: true
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - owners
      security:
      - cookieAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSafeLastStatusList'
          description: Paginated list of Safe accounts that have the given address as their owner
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeErrorResponse'
          description: Owner address checksum not valid
      path: /tx-service/eth/api/v2/owners/{address}/safes/
      title: List Safes from a Specific Owner
      additionalInfo: ''
components:
  schemas:
    SafeLastStatus:
      type: object
      properties:
        address:
          type: string
        owners:
          type: array
          items:
            type: string
        threshold:
          type: integer
        nonce:
          type: integer
        masterCopy:
          type: string
        fallbackHandler:
          type: string
        guard:
          type:
          - string
          - 'null'
        moduleGuard:
          type:
          - string
          - 'null'
        enabledModules:
          type: array
          items:
            type: string
      required:
      - address
      - enabledModules
      - fallbackHandler
      - guard
      - masterCopy
      - moduleGuard
      - nonce
      - owners
      - threshold
    PaginatedSafeLastStatusList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/SafeLastStatus'
    OwnerResponse:
      type: object
      properties:
        safes:
          type: array
          items:
            type: string
      required:
      - safes
    CodeErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        arguments:
          type: array
          items: {}
      required:
      - arguments
      - code
      - message
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
