openapi: 3.2.0
info:
  title: Safe Transaction Service Analytics API
  version: 6.3.0
  description: API to keep track of transactions sent via Safe smart contracts
tags:
- name: Analytics
paths:
  /tx-service/eth/api/v2/analytics/multisig-transactions/by-origin/:
    get:
      operationId: analytics_multisig_transactions_by_origin_retrieve
      tags:
      - Analytics
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
      path: /tx-service/eth/api/v2/analytics/multisig-transactions/by-origin/
      title: ''
      additionalInfo: ''
      summary: Analytics multisig transactions by origin retrieve
      x-summary-source: derived
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
